# Generated by Django 2.1.1 on 2018-09-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, verbose_name='账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='邮箱')),
                ('nickName', models.CharField(max_length=20, verbose_name='昵称')),
                ('introduc', models.CharField(blank=True, max_length=256, verbose_name='简介')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('editDate', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('token', models.CharField(blank=True, max_length=256, verbose_name='token')),
                ('pushToken', models.CharField(blank=True, max_length=256, verbose_name='推送token')),
            ],
        ),
    ]
